# Parameters for the example pipeline
# Split ratio between testing data and training data
example_test_data_ratio: 0.2
# Parameter to train a random forest classifier
example_num_trees: 10
test_size: 0.2
random_state: 42
ngram_range_min: 1
ngram_range_max: 2
max_features: 100000
max_iter: 1000
C: 1